#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width       0
bspc config window_gap           90
bspc config normal_border_color  \#253047
bspc config focused_border_color \#253047

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Downloads/Mountain.png &
xrandr --output DP-4 --mode 1920x1080 --rate 164.97 &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true &
picom --experimental-backends &
dunst &
~/.config/polybar/launch.sh
eww daemon &
